global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8888']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['event-service:8083']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']

  - job_name: 'profil-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['profil-service:8085']

  - job_name: 'registration-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['registration-service:8082']
