apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - port: 8081
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/db_auth_service
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  ports:
  - port: 8083
  selector:
    app: event-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: event-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/event_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: JWT_SECRET
          value: votre_super_secret_key_pour_les_tokens_jwt_changez_cela_en_production
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
  - port: 8080
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/notification_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: profil-service
spec:
  ports:
  - port: 8085
  selector:
    app: profil-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profil-service
spec:
  selector:
    matchLabels:
      app: profil-service
  template:
    metadata:
      labels:
        app: profil-service
    spec:
      containers:
      - name: profil-service
        image: profil-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/profile_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  ports:
  - port: 8082
  selector:
    app: registration-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
spec:
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - name: registration-service
        image: registration-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/registration_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30088
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        imagePullPolicy: Never
        env:
        - name: AUTH_SERVICE_URL
          value: http://auth-service:8081
        - name: REGISTRATION_SERVICE_URL
          value: http://registration-service:8082
        - name: EVENT_SERVICE_URL
          value: http://event-service:8083
        - name: NOTIFICATION_SERVICE_URL
          value: http://notification-service:8080
        - name: PROFIL_SERVICE_URL
          value: http://profil-service:8085
        ports:
        - containerPort: 8888
