apiVersion: v1
kind: Service
metadata:
  name: profil-service
spec:
  ports:
  - port: 8085
  selector:
    app: profil-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profil-service
spec:
  selector:
    matchLabels:
      app: profil-service
  template:
    metadata:
      labels:
        app: profil-service
    spec:
      containers:
      - name: profil-service
        image: profil-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/profile_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        ports:
        - containerPort: 8085
