apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  ports:
  - port: 8082
  selector:
    app: registration-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
spec:
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - name: registration-service
        image: registration-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/registration_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        ports:
        - containerPort: 8082
